### ISSUE TITLE
Al editar un registro, TemplateBuilder falla al procesar campos tipo DATETIME fuera de los timestamps.

### ISSUE THREAD

**Issue by armincifuentes** [leonardoDavid/LaCrud#4]
Al intentar editar un registro que contenga un campo tipo `DATETIME` que **no corresponda a un timestamp**, TemplateBuilder falla al instanciar la columna y no encuentra el método `->format()`.

El la salida de Laravel indica:

```
FatalErrorException in TemplateBuilder.php line 423:
Call to a member function format() on a non-object
```

**Comment by armincifuentes** [comment]
El error no es exclusivo a los campos tipo `DATETIME`, también están afectados los tipos `TIMESTAMP` y `DATE` (aunque este último con un tipo diferente de error, que debería manejarse en un nuevo issue)

**Comment by devswert** [comment]
Ambos bugs estan resueltos, por favor ejecutar `composer update` y posterior `php artisan vendor:publish --force`, ya que se actualizaron unas vistas también
