### ISSUE TITLE
[ErrorException in Utils.php line 17:] Don't exist a 'forms' folder in your Theme for LaCrud

### ISSUE THREAD

**Issue by yonkishum** [leonardoDavid/LaCrud#5]
Saludos, vengo a poner este problema que me ocasiona cuando intento agregar el Tema al CRUD Generator. estoy usando la misma configuración que esta en el readme

**Comment by devswert** [comment]
¡Hola! ¿Estás generando tu propio tema, no? Resulta que un template de LaCrud requiere de ciertos archivos para funcionar y desplegar los formularios. Estoy trabajando en la documentación para dejar detalle completo de cómo crear tu propio tema para LaCrud. Dejaré cerrado este issue y comentaré el mismo cuando actualice esa sección de la documentación.

**Comment by yonkishum** [comment]
Hmmm no exactamente estoy usando mi propio tema, quiero por lo menos ver mejor la interfaz de CRUD Generator. porque me sale una página cuando intento de acceder pero sin CSS y no puedo distinguir entre los elementos del CRUD Generator.

Vi en LaCRUD esta un template pero cuando quiero invocarlo me sale el mismo problema. ¿Alguna solución para esto?

**Comment by devswert** [comment]
Mmm...... Aun no entiendo muy bien tu problema, si quieres agregar un nuevo tema para LaCrud debes tener los mismo archivos que están en el template base, modificando las hojas de estilo que estimes convenientes y el HTML, tiene más detalles que tomar en cuenta, así que no te aconsejo aun que lo hagas para evitar dolores de cabeza, hasta que tenga bien documentada esta sección.
Por otra parte, si solo quieres usar el Template base de LaCrud puedes ejecutar `php artisan vendor:publish --force` para que reemplace y copie todo el template base.

**Comment by yonkishum** [comment]
Te dejaré este screenshoot para ver si me puedes ayudar :), osea no puedo ver correctamente el CRUD. y cuando agrego la opción del Tema que trae por defecto laCRUD  y me sale el error que te estoy comentando.
![screenshot - 22-05-2015 05_07_40 p m](https://cloud.githubusercontent.com/assets/6378461/7780143/27f56be0-00a5-11e5-8427-11d55e37de1e.png)

lo siento si ve que no tengo el Windows Activado.

**Comment by devswert** [comment]
Prueba lo siguiente, ve a la carpeta public y borra el directorio LaCrud, y luego a resources/vendor/ y también borra el directorio LaCrud. Ahora, ejecuta `php artisan vendor:publish` .
Con eso te debería funcionar, si no, revisa por la consola del navegador si los assets responden con 403, eso quiere decir que tienes problemas de permisos en donde estas desplegando tu app.

**Comment by yonkishum** [comment]
listo :) funciona perfectamente :+1:
