### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by ayalaarevalo** [leonardoDavid/LaCrud#7]
Actualizaras LaCrud con la nueva version de laravel

**Comment by devswert** [comment]
Hola!
Lo probé en un proyecto con Laravel 5.1 y nada se rompió, por lo menos a mi, si tienes algún problema déjalo aquí y lo solucionare, dentro de esta semana volveré al desarrollo de LaCrud, ya que estuve un poco ausente durante un tiempo.

Saludos!
